### ISSUE TITLE
GitLens Support

### ISSUE THREAD

**Issue by jneate** [iambenzo/vscode-theme-nyx#1]
Hi,

The GitLens information doesn't work the greatest with the current version (0.0.4) of the theme, can you investigate please?

From the GitLens documentation:

Name | Description
-- | --
gitlens.gutterBackgroundColor | Specifies the background color of the gutter blame annotations
gitlens.gutterForegroundColor | Specifies the foreground color of the gutter blame annotations
gitlens.gutterUncommittedForegroundColor | Specifies the foreground color of an uncommitted line in the gutter blame annotations
gitlens.trailingLineBackgroundColor | Specifies the background color of the trailing blame annotation
gitlens.trailingLineForegroundColor | Specifies the foreground color of the trailing blame annotation
gitlens.lineHighlightBackgroundColor | Specifies the background color of the associated line highlights in blame annotations
gitlens.lineHighlightOverviewRulerColor | Specifies the overview ruler color of the associated line highlights in blame annotations

Thanks,
James

**Comment by iambenzo** [comment]
As the extension is very popular, I will certainly look into this. Thanks 😄

**Comment by iambenzo** [comment]
I've made some slight adjustments for the Git Lens extension...can you confirm that everything is legible for you?
